gui:
  authorColors: 
    'JacobRosenlund': '#AA2222'
  branchColors: {}
  mouseEvents: true
  theme: 
    activeBorderColor:
      - blue
      - bold
    selectedLineBgColor:
      - '#7b97c3'
  commitLength:
    show: true
  showBottomLine: true
  spinner:
    frames:
      - ''
      - ''
      - ''
      - ''
      - ''
      - ''
    rate: 75
git:
  mainBranches:
    - master
    - main
  parseEmoji: true

