# yazi.toml
[mgr]
show_hidden = true

[[plugin.prepend_previewers]]
name = "*.tar*"
run = 'piper --format=url -- tar tf "$1"'

[[plugin.prepend_previewers]]
name = "*.md"
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

[[plugin.prepend_previewers]]
name = "*.csv"
run = 'miller "$1"'

[[plugin.append_previewers]]
name = "*"
run = 'piper -- hexyl --border=none --terminal-width=$w "$1"'

[opener]
play = [
  { run = 'vlc "$@"', orphan = true, for = "unix" }
]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open" }
]

[open]
prepend_rules = [
]
append_rules = [
  { name = "*", use = "edit" }
]
